//Do not edit this file (unless you know what you are doing)

#ifndef ODE_SOLVER_H
#define ODE_SOLVER_H

#include"matrix.h"

matrix *solve_ode(double, double, double, matrix &, matrix &); // throw (char*);
matrix diff(double, matrix &, matrix &);

#endif